// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmbjkjfgYoQd3tU1BMajnahwXS5zYlV2k',
    appId: '1:938644119022:web:079ac874b7ac44ef8642ff',
    messagingSenderId: '938644119022',
    projectId: 'fleetmonitor-aab6a',
    authDomain: 'fleetmonitor-aab6a.firebaseapp.com',
    storageBucket: 'fleetmonitor-aab6a.firebasestorage.app',
    measurementId: 'G-EGW6VR4J51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYNtXGkWnMGKw_3qLGSMF4Tc0c0c9txU',
    appId: '1:938644119022:android:dd4207592be8f0ac8642ff',
    messagingSenderId: '938644119022',
    projectId: 'fleetmonitor-aab6a',
    storageBucket: 'fleetmonitor-aab6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgxOQVvsA3UUbZFvmyrzUycAGU32j8FbU',
    appId: '1:938644119022:ios:24a1fe2cf2fae5fa8642ff',
    messagingSenderId: '938644119022',
    projectId: 'fleetmonitor-aab6a',
    storageBucket: 'fleetmonitor-aab6a.firebasestorage.app',
    iosBundleId: 'com.example.fleetmonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgxOQVvsA3UUbZFvmyrzUycAGU32j8FbU',
    appId: '1:938644119022:ios:24a1fe2cf2fae5fa8642ff',
    messagingSenderId: '938644119022',
    projectId: 'fleetmonitor-aab6a',
    storageBucket: 'fleetmonitor-aab6a.firebasestorage.app',
    iosBundleId: 'com.example.fleetmonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmbjkjfgYoQd3tU1BMajnahwXS5zYlV2k',
    appId: '1:938644119022:web:1a6905472a17be2f8642ff',
    messagingSenderId: '938644119022',
    projectId: 'fleetmonitor-aab6a',
    authDomain: 'fleetmonitor-aab6a.firebaseapp.com',
    storageBucket: 'fleetmonitor-aab6a.firebasestorage.app',
    measurementId: 'G-T80GQTBYK7',
  );
}
